name: Docker Image CI

on:
  push:
    branches: "*"
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build docker/8.3 --file docker/8.3/Dockerfile --tag portfolio-app:$(date +%s) --build-arg WWWGROUP=1000